import { QueueView } from "QueueView.slint";
import { TabSelectorView } from "TabSelectorView.slint";
import { MainView } from "MainView.slint";
import { NowPlayingView } from "NowPlayingView.slint";
import { PlayerView } from "PlayerView.slint";
import {
    CurrentSong,
    Song,
    Tabs,
    Theme,
    PlaylistMinimal,
    Playlist,
} from "Types.slint";
import "../assets/NotoSans.ttf";
import "../assets/JetbrainsMono.ttf";


export component AuroraPlayer inherits Window {
    callback queue-click(int);
    callback queue-remove(int);
    callback queue-clear();
    callback prev();
    callback pause();
    callback next();
    callback seek(float);
    callback search(string, string);
    callback add(string);
    callback refresh-playlists();
    callback select-playlist(string);
    callback replace-queue(Playlist);

    in-out property <string> Title: "Nothing Playing";
    in-out property <string> Artists: "No artist";
    in-out property <image> AlbumArt: @image-url("../assets/placeholder.png");
    in-out property <int> position: 0;
    in-out property <bool> is_paused: true;
    in-out property <int> duration: 0;

    in-out property <[Song]> queue;
    in-out property <[Song]> searchResults;
    in-out property <[PlaylistMinimal]> playlistsList;
    in-out property <Playlist> playlistResult: {
        title: "Playlist Test",
        id:"id",
        songs: [
            { album-art:  @image-url("../assets/placeholder.png"), title: "Song", artists: "Artist" }
        ]
    };

    in-out property <Tabs> active-view: Tabs.Playlists;

    title: "Aurora Player";

    min-height: 650px;
    min-width: 1155px;
    preferred-height: 800px;
    preferred-width: 1422px;

    default-font-family: "Noto Sans JP";

    Rectangle {
        background: Theme.bg0;
        HorizontalLayout {
            spacing: 5px;
            padding: 5px;
            VerticalLayout {
                spacing: 5px;

                QueueView {
                    queue: root.queue;
                    queue-click(n) => {
                        root.queue-click(n)
                    }
                    queue-remove(n) => {
                        root.queue-remove(n)
                    }
                    queue-clear => {
                        root.queue-clear()
                    };
                }

                VerticalLayout {
                    NowPlayingView {
                        Title: root.Title;
                        Artists: root.Artists;
                        AlbumArt: root.AlbumArt;

                        width: 400px;
                        height: 100px;
                    }
                }
            }

            VerticalLayout {
                spacing: 5px;

                TabSelectorView {
                    active-view <=> root.active-view;
                    refresh-playlists => {
                        refresh-playlists()
                    }
                }

                MainView {
                    active-view: root.active-view;
                    searchResults: root.searchResults;
                    current-playlist: root.playlistResult;
                    playlists: root.playlistsList;
                    query-submit(q, e) => {
                        search(q, e);
                    }
                    add(s) => {
                        root.add(s);
                    }
                    get-playlist(s) => {
                        select-playlist(s)
                    }
                    replace-queue(pl) => {
                        root.replace-queue(pl)
                    }
                }

                PlayerView {
                    pause => {
                        root.pause()
                    }
                    next => {
                        root.next()
                    }
                    prev => {
                        root.prev()
                    }
                    seek(value) => {
                        seek(value);
                    }
                    value <=> position;
                    duration: root.duration;
                    is-paused: root.is_paused;
                }
            }
        }
    }
}
