import { HorizontalBox, VerticalBox } from "std-widgets.slint";
import { Song, PlaylistMinimal, Theme } from "Types.slint";

export component ScrollView inherits Rectangle {
    in property <length> content-height;

    in property <int> direction: 1;

    clip: true;

    changed content-height => {
        touch.viewport-y = 0
    }

    touch := TouchArea {
        width: parent.width;
        height: parent.height;

        property <length> viewport-y;
        scroll-event(event) => {
            viewport-y = min(0px, max(-(content-height - parent.height), viewport-y - (root.direction * event.delta-y)));

            return accept;
        }

        rect := Rectangle {
            y: touch.viewport-y;
            width: parent.width;
            VerticalLayout {
                @children
            }
        }
    }
}

export component CustomSlider inherits Rectangle {

    in property <bool> enabled: true;
    in property <int> minimum: 0;
    in property <int> maximum: 100;

    in-out property <int> value: 0;
    in-out property <int> displayValue: 0;
    in-out property <int> displayHoverValue: 0;

    in property <int> step: 10000;
    callback released(float);

    private property <float> normalizedDisplayValue: (displayValue - minimum) / (maximum - minimum);
    private property <float> normalizedDisplayHoverValue: (displayHoverValue - minimum) / (maximum - minimum);
    private property <float> normalizedValue: (value - minimum) / (maximum - minimum);
    private property <bool> pressed: false;

    animate normalizedDisplayValue {
        duration: 190ms;
        easing: ease;
    }

    changed value => {
        if !root.pressed {
            root.displayValue = root.value;
        }
    }

    height: 40px;
    track := Rectangle {
        y: (parent.height - self.height) / 2;
        height: touch.has-hover ? 12px : 6px;
        background: Theme.bgd3;
        border-radius: touch.has-hover ? 6px : 3px;

        animate height, border-radius { duration: 100ms; }

        fillHover := HorizontalBox {
            alignment: LayoutAlignment.start;
            padding: 0px;
            width: track.width;
            visible: touch.has-hover;

            Rectangle {
                width: track.width * root.normalizedDisplayHoverValue;
                background: Theme.bgd4;
                border-radius: track.border-radius;
            }
        }

        fill := HorizontalBox {
            alignment: LayoutAlignment.start;
            padding: 0px;
            width: track.width;

            Rectangle {
                width: track.width * root.normalizedDisplayValue;
                background: Theme.acct;
                border-radius: track.border-radius;
            }
        }
    }

    touch := TouchArea {
        enabled: root.enabled;
        height: self.has-hover ? 12px : 6px;

        pointer-event(event) => {
            if (event.kind == PointerEventKind.down || event.kind == PointerEventKind.move) {
                if (self.pressed) {
                    root.pressed = true;
                    root.displayValue = root.minimum + (root.maximum - root.minimum) * clamp(self.mouse-x / root.width, 0, 1);
                    root.displayHoverValue = root.minimum + (root.maximum - root.minimum) * clamp(self.mouse-x / root.width, 0, 1);
                } else if (self.has-hover) {
                    root.displayHoverValue = root.minimum + (root.maximum - root.minimum) * clamp(self.mouse-x / root.width, 0, 1);
                }
            }
            if (event.kind == PointerEventKind.up) {
                root.pressed = false;
                root.released(root.displayValue);
            }
        }
    }

    /*
    focus-scope := FocusScope {
        enabled: root.enabled;

        key-pressed(event) => {
            if (event.text == Key.LeftArrow) {
                root.displayValue = max(root.minimum, root.displayValue - root.step);
                root.released(root.displayValue);
                return accept;
            }
            if (event.text == Key.RightArrow) {
                root.displayValue = min(root.maximum, root.displayValue + root.step);
                root.released(root.displayValue);
                return accept;
            }
            if (event.text == Key.Home) {
                root.displayValue = root.minimum;
                root.released(root.displayValue);
                return accept;
            }
            if (event.text == Key.End) {
                root.displayValue = root.maximum;
                root.released(root.displayValue);
                return accept;
            }
            return reject;
        }

        key-released(event) => {
            if (event.text == Key.LeftArrow || event.text == Key.RightArrow || event.text == Key.Home || event.text == Key.End) {
                return accept;
            }
            return reject;
        }
    }
    */
}

export component ComboBox {
    in-out property <[string]> model;
    in-out property <string> current;
    private property <bool> expanded: false;

    Rectangle {
        width: parent.width;
        height: parent.height;
        background: Theme.bgd2;
        border-radius: 10px;
        TouchArea {
            width: parent.width;
            height: parent.height;
            clicked => {
                root.expanded = !root.expanded;
                if root.expanded {
                    box.height = model.length * 50px + 15px;
                } else {
                    box.height = 0;
                }
            }
        }

        HorizontalLayout {
            padding: 10px;
            Text {
                text: root.current;
                vertical-alignment: center;
                font-size: 20px;
                color: Theme.txt1;
            }

            Text {
                text: root.expanded ? "▲" : "▼";
                horizontal-alignment: right;
                vertical-alignment: center;
                color: Theme.txt1;
            }
        }
    }

    box := Rectangle {
        background: Theme.bgd2;
        border-width: 2px;
        border-color: Theme.acct;
        y: parent.height + 5px;
        height: 0px;
        border-radius: 10px;
        clip: true;
        animate height {
            duration: 100ms;
            easing: ease-in-out-quad;
        }
        drop-shadow-color: Theme.bgd0;
        drop-shadow-blur: 10px;
        TouchArea { }

        VerticalLayout {
            spacing: 5px;
            padding: 5px;
            width: parent.width;
            for item[i] in model: Rectangle {
                width: parent.width - 10px;
                border-radius: 10px;
                height: 50px;

                background: item == root.current ? Theme.bgd3 : Theme.bgd2;
                TouchArea {
                    width: parent.width;
                    height: parent.height;
                    clicked => {
                        root.current = item;
                        root.expanded = false;
                        box.height = 0;
                    }
                }

                HorizontalBox {
                    padding: 10px;
                    Text {
                        text: item;
                        vertical-alignment: center;
                        font-size: 15px;
                        color: Theme.txt1;
                    }
                }
            }
        }
    }
}

export component PlList inherits VerticalLayout {
    in property <[PlaylistMinimal]> items;
    callback item-clicked(string);
    Rectangle {
        border-radius: 10px;
        clip: true;
        ScrollView {
            content-height: 65px * items.length - 5px;
            direction: -1;
            box := VerticalBox {
                spacing: 5px;
                padding: 0px;
                for item[i] in items: Rectangle {
                    height: 70px;
                    border-radius: 10px;
                    background: touch.has-hover ? Theme.bgd3 : Theme.bgd2;
                    animate background { duration: 100ms; }
                    touch := TouchArea {
                        clicked => {
                            item-clicked(item.id);
                        }
                    }

                    HorizontalLayout {
                        padding: 5px;
                        padding-right: 20px;
                        padding-left: 20px;
                        Rectangle {
                            HorizontalLayout {
                                Text {
                                    text: item.title;
                                    color: Theme.txt1;
                                    font-size: 30px;
                                    horizontal-alignment: left;
                                    vertical-alignment: center;
                                }

                                Text {
                                    text: item.length + (item.length == 1 ? "  song." : " songs.");
                                    color: Theme.txt2;
                                    font-size: 20px;
                                    horizontal-alignment: right;
                                    vertical-alignment: center;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

export component SongList inherits VerticalLayout {
    in property <[Song]> items;
    callback item-clicked(string);
    Rectangle {
        border-radius: 10px;
        clip: true;
        ScrollView {
            content-height: 65px * items.length - 5px;
            direction: -1;
            box := VerticalBox {
                spacing: 5px;
                padding: 0px;
                for item[i] in items: Rectangle {
                    border-radius: 10px;
                    background: touch.has-hover ? Theme.bgd3 : Theme.bgd2;
                    animate background { duration: 100ms; }
                    touch := TouchArea {
                        clicked => {
                            item-clicked(item.id);
                        }
                    }

                    HorizontalLayout {
                        padding: 5px;
                        padding-right: 20px;
                        spacing: 10px;
                        Rectangle {
                            height: 50px;
                            width: 50px;
                            border-radius: 10px;
                            clip: true;
                            Image {
                                source: item.album_art;
                                height: parent.width;
                                width: parent.height;
                            }
                        }

                        Text {
                            text: item.title;
                            color: Theme.txt1;
                            font-size: 20px;
                            vertical-alignment: center;
                            horizontal-alignment: left;
                        }

                        Text {
                            text: item.artists;
                            color: Theme.txt2;
                            font-size: 15px;
                            vertical-alignment: center;
                            horizontal-alignment: right;
                        }
                    }
                }
            }
        }
    }
}
