import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { ComboBox, SongList, PlList } from "CustomComp.slint";
import { Song, PlaylistMinimal, Playlist, Theme }from "Types.slint";

export component SearchView inherits VerticalBox {
    in-out property <string> searchMode: "By Title";
    in-out property <string> query: "";
    in property <[Song]> searchResults;
    callback submit(string, string);
    callback item-clicked(string);

    VerticalLayout {
        spacing: 5px;

        HorizontalLayout {
            spacing: 5px;
            Rectangle {
                border-radius: 10px;
                height: 50px;
                background: Theme.bg1;
                border-width: 1px;
                HorizontalBox {
                    padding: 10px;

                    Text {
                        text: " ";
                        height: parent.height - 20px;
                        width: parent.height - 20px;
                        font-size: 20px;
                        vertical-alignment: center;
                        horizontal-alignment: center;
                        color: Theme.bg4;
                    }

                    TextInput {
                        font-size: 20px;
                        vertical-alignment: center;
                        color: Theme.text;
                        text <=> query;
                        accepted => {
                            submit(query, searchMode);
                        }
                    }
                }
            }

            ComboBox {
                model: ["By Artist", "By Title"];
                current <=> searchMode;
                changed current => {
                    submit(query, searchMode);
                }
            }
        }

        SongList {
            z: -1;
            items: searchResults;
            item-clicked(id) => {
                item-clicked(id);
            }
        }
    }
}

export component PlaylistView inherits VerticalBox {
    in property <[PlaylistMinimal]> playlists;
    in-out property <bool> in-playlist;
    in-out property <Playlist> current-playlist;
    callback get-playlist(string);
    padding: 10px;
    // Text {
    //     text: "Playlists";
    //     color: Theme.text;
    //     font-size: 30px;
    // }

    if (!in-playlist): PlList {
        items: playlists;
        item-clicked(id) => {
            get-playlist(id);
            in-playlist = true;
        }
    }

    if (in-playlist): VerticalLayout {
        Text {
            text: current-playlist.title;
            color: Theme.text;
            font-size: 30px;
        }

        SongList {
            items: current-playlist.songs;
        }
    }
}

export component MainView inherits Rectangle {
    background: Theme.bg2;
    border-radius: 15px;
    in property <string> active-view;
    in property <[Song]> searchResults;
    in property <[PlaylistMinimal]> playlists;
    in property <Playlist> current-playlist;
    in property <bool> searchOverflow;
    callback query-submit(string, string);
    callback add(string);
    callback get-all-playlists();
    callback get-playlist(string);

    SearchView {
        visible: active-view == "Search";
        searchResults: root.searchResults;
        submit(q, m) => {
            query-submit(q, m);
            debug(q, m);
        }
        item-clicked(id) => {
            add(id);
        }
    }

    plView := PlaylistView {
        visible: active-view == "Playlists";
        current-playlist: root.current-playlist;
        playlists: root.playlists;
        get-playlist(id) => {
            get-playlist(id)
        }
    }

    changed active-view => {
        plView.in-playlist = false
    }
}
