import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { ComboBox, SongList, PlList } from "CustomComp.slint";
import { Song, PlaylistMinimal, Playlist, Theme, Tabs }from "Types.slint";

export component SearchView inherits VerticalBox {
    in-out property <string> searchMode: "By Title";
    in-out property <string> query: "";
    in property <[Song]> searchResults;
    callback submit(string, string);
    callback item-clicked(string);
    padding: 5px;

    VerticalLayout {
        spacing: 5px;

        HorizontalLayout {
            spacing: 5px;
            Rectangle {
                border-radius: 10px;
                height: 60px;
                background: Theme.bg1;
                border-width: 1px;
                HorizontalBox {
                    padding: 10px;

                    Text {
                        text: " ";
                        height: parent.height - 20px;
                        width: parent.height - 20px;
                        font-size: 30px;
                        vertical-alignment: center;
                        horizontal-alignment: center;
                        color: Theme.bg4;
                        font-family: "JetbrainsMono Nerd Font";
                    }

                    TextInput {
                        font-size: 30px;
                        vertical-alignment: center;
                        color: Theme.text;
                        text <=> query;
                        accepted => {
                            submit(query, searchMode);
                        }
                    }
                }
            }

            ComboBox {
                height: 60px;
                width: 160px;
                model: ["By Artist", "By Title"];
                current <=> searchMode;
                changed current => {
                    submit(query, searchMode);
                }
            }
        }

        SongList {
            z: -1;
            items: searchResults;
            item-clicked(id) => {
                item-clicked(id);
            }
        }
    }
}

export component PlaylistView inherits VerticalBox {
    in property <[PlaylistMinimal]> playlists;
    in-out property <bool> in-playlist;
    in-out property <Playlist> current-playlist;
    callback get-playlist(string);
    callback item-clicked(string);
    callback replace-queue(Playlist);
    padding: 5px;

    Rectangle {
        PlList {
            states [
                visible when !in-playlist: {
                    opacity: 1;
                    visible: true;
                    in-out {
                        animate opacity { duration: 100ms; }
                    }
                }
                invisible when in-playlist: {
                    opacity: 0;
                    visible: false;
                    in-out {
                        animate opacity { duration: 100ms; }
                    }
                }
            ]
            items: playlists;
            item-clicked(id) => {
                get-playlist(id);
                in-playlist = true;
            }
        }

        VerticalLayout {
            states [
                visible when in-playlist: {
                    opacity: 1;
                    visible: true;
                    in-out {
                        animate opacity { duration: 100ms; }
                    }
                }
                invisible when !in-playlist: {
                    opacity: 0;
                    visible: false;
                    in-out {
                        animate opacity { duration: 100ms; }
                    }
                }
            ]
            spacing: 10px;
            padding: 0px;

            HorizontalLayout {
                padding: 0px;
                height: 60px;
                spacing: 5px;
                Rectangle {
                    height: parent.height;
                    width: parent.height;
                    background: touch.has-hover ? Theme.bg0 : Theme.bg1;
                    animate background { duration: 200ms; }
                    border-radius: 10px;
                    Text {
                        height: parent.height;
                        width: parent.width;
                        text: "";
                        font-family: "JetbrainsMono Nerd Font Mono";
                        font-size: 40px;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        color: Theme.text;
                    }

                    touch := TouchArea {
                        clicked => {
                            in-playlist = false;
                        }
                    }
                }

                Rectangle {
                    height: parent.height;
                    width: parent.height;
                    background: touch2.has-hover ? Theme.bg0 : Theme.bg1;
                    animate background { duration: 200ms; }
                    border-radius: 10px;
                    Text {
                        height: parent.height;
                        width: parent.width;
                        text: "";
                        font-family: "JetbrainsMono Nerd Font Mono";
                        font-size: 40px;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        color: Theme.text;
                    }

                    touch2 := TouchArea {
                        clicked => {
                            replace-queue(root.current-playlist);
                        }
                    }
                }

                Rectangle {
                    background: Theme.bg1;
                    border-radius: 10px;
                    HorizontalLayout {
                        padding: 10px;
                        padding-right: 20px;
                        padding-left: 20px;
                        alignment: space-between;
                        Text {
                            text: current-playlist.title;
                            color: Theme.text;
                            font-size: 30px;
                            vertical-alignment: center;
                            horizontal-alignment: left;
                        }

                        Text {
                            private property <string> len: current-playlist.songs.length;
                            text: len + (len == 1 ? " song" : " songs");
                            color: Theme.text2;
                            font-size: 20px;
                            vertical-alignment: center;
                            horizontal-alignment: right;
                        }
                    }
                }
            }

            SongList {
                items: current-playlist.songs;
                item-clicked(id) => {
                    item-clicked(id);
                }
            }
        }
    }
}

export component MainView inherits Rectangle {
    background: Theme.bg2;
    border-radius: 15px;
    in property <Tabs> active-view;
    in property <[Song]> searchResults;
    in property <[PlaylistMinimal]> playlists;
    in property <Playlist> current-playlist;
    in property <bool> searchOverflow;
    callback query-submit(string, string);
    callback add(string);
    callback get-all-playlists();
    callback get-playlist(string);
    callback replace-queue(Playlist);

    SearchView {
        states [
            visible when active-view == Tabs.Search: {
                opacity: 1;
                visible: true;
                in-out {
                    animate opacity { duration: 100ms; }
                }
            }
            invisible when active-view != Tabs.Search: {
                opacity: 0;
                visible: false;
                in-out {
                    animate opacity { duration: 100ms; }
                }
            }
        ]

        searchResults: root.searchResults;
        submit(q, m) => {
            query-submit(q, m);
            debug(q, m);
        }
        item-clicked(id) => {
            add(id);
        }
    }

    plView := PlaylistView {
        states [
            visible when active-view == Tabs.Playlists: {
                opacity: 1;
                visible: true;
                in-out {
                    animate opacity { duration: 100ms; }
                }
            }
            invisible when active-view != Tabs.Playlists: {
                opacity: 0;
                visible: false;
                in-out {
                    animate opacity { duration: 100ms; }
                }
            }
        ]
        current-playlist: root.current-playlist;
        playlists: root.playlists;
        get-playlist(id) => {
            get-playlist(id);
        }
        item-clicked(id) => {
            add(id);
        }
        replace-queue(pl) => {
            replace-queue(pl);
        }
    }
}
