import { Slider, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { CustomSlider } from "CustomComp.slint";
import { Theme } from "Types.slint";

export global TimeUtils {
    pure public function ms_to_minsec(ms: int) -> string {
        let total_sec: int = ms / 1000;
        let min_str: int = total_sec / 60;
        let sec: int = Math.mod(total_sec, 60);
        let sec_str: string = sec < 10 ? "0" + sec : sec;
        return min_str + ":" + sec_str;
    }
}

export component PlayerView inherits Rectangle {
    height: 100px;
    background: Theme.bgd2;
    border-radius: 15px;

    in-out property <int> value;
    in property <int> duration;
    in property <bool> is-paused;
    in-out property <bool> shuffle: false;
    in-out property <int> repeat: 0;
    in-out property <float> volume: 1.0;

    callback prev();
    callback pause();
    callback next();
    callback seek(float);
    callback set-shuffle(bool);
    callback set-repeat(int);
    callback set-volume(float);

    VerticalLayout {
        padding: 5px;
        spacing: 0px;

        HorizontalLayout {
            padding: 6px;
            spacing: 0px;

            VerticalLayout {
                width: 80px;
                alignment: LayoutAlignment.center;
                padding: 5px;
                Text {
                    text: TimeUtils.ms_to_minsec(value);
                    font-size: 18px;
                    color: Theme.txt1;
                    horizontal-alignment: left;
                }
            }

            VerticalLayout {
                horizontal-stretch: 1;
                alignment: LayoutAlignment.center;
                HorizontalLayout {
                    alignment: LayoutAlignment.center;
                    spacing: 8px;

                    Rectangle {
                        width: 36px;
                        height: 36px;
                        border-radius: 18px;
                        background: shuffleTA.has-hover ? Theme.bgd4 : Theme.bgd3;
                        animate background { duration: 100ms; }
                        Text {
                            vertical-alignment: TextVerticalAlignment.center;
                            horizontal-alignment: TextHorizontalAlignment.center;
                            width: 36px;
                            height: 36px;
                            text: "\u{f049d}";
                            font-size: 22px;
                            font-family: "JetBrainsMono NFP";
                            color: root.shuffle ? Theme.acct : Theme.txt2;
                        }
                        shuffleTA := TouchArea {
                            height: parent.height;
                            width: parent.width;
                            clicked => {
                                root.shuffle = !root.shuffle;
                                set-shuffle(root.shuffle);
                            }
                        }
                    }

                    Rectangle {
                        width: 40px;
                        height: 40px;
                        border-radius: 20px;
                        background: prevTA.has-hover ? Theme.bgd4 : Theme.bgd3;
                        animate background { duration: 100ms; }
                        Text {
                            vertical-alignment: TextVerticalAlignment.center;
                            horizontal-alignment: TextHorizontalAlignment.center;
                            width: 40px;
                            height: 40px;
                            text: "\u{f04ae}";
                            font-size: 30px;
                            font-family: "JetBrainsMono NFP";
                            color: Theme.btns;
                        }
                        prevTA := TouchArea {
                            height: parent.height;
                            width: parent.width;
                            clicked => { prev() }
                        }
                    }

                    Rectangle {
                        width: 40px;
                        height: 40px;
                        border-radius: 20px;
                        background: playTA.has-hover ? Theme.bgd4 : Theme.bgd3;
                        animate background { duration: 100ms; }
                        Text {
                            vertical-alignment: TextVerticalAlignment.center;
                            horizontal-alignment: TextHorizontalAlignment.center;
                            width: 40px;
                            height: 40px;
                            text: root.is-paused ? "\u{f040a}" : "\u{f03e4}";
                            font-size: root.is-paused ? 25px : 30px;
                            font-family: "JetBrainsMono NFP";
                            color: Theme.btns;
                        }
                        playTA := TouchArea {
                            height: parent.height;
                            width: parent.width;
                            clicked => { pause(); }
                        }
                    }

                    Rectangle {
                        width: 40px;
                        height: 40px;
                        border-radius: 20px;
                        background: nextTA.has-hover ? Theme.bgd4 : Theme.bgd3;
                        animate background { duration: 100ms; }
                        Text {
                            vertical-alignment: TextVerticalAlignment.center;
                            horizontal-alignment: TextHorizontalAlignment.center;
                            width: 40px;
                            height: 40px;
                            text: "\u{f04ad}";
                            font-size: 30px;
                            font-family: "JetBrainsMono NFP";
                            color: Theme.btns;
                        }
                        nextTA := TouchArea {
                            height: parent.height;
                            width: parent.width;
                            clicked => { next() }
                        }
                    }

                    Rectangle {
                        width: 36px;
                        height: 36px;
                        border-radius: 18px;
                        background: repeatTA.has-hover ? Theme.bgd4 : Theme.bgd3;
                        animate background { duration: 100ms; }
                        Text {
                            vertical-alignment: TextVerticalAlignment.center;
                            horizontal-alignment: TextHorizontalAlignment.center;
                            width: 36px;
                            height: 36px;
                            text: root.repeat == 1 ? "\u{f0457}" : "\u{f0456}";
                            font-size: 22px;
                            font-family: "JetBrainsMono NFP";
                            color: root.repeat == 1 ? Theme.acct : Theme.txt2;
                        }
                        repeatTA := TouchArea {
                            height: parent.height;
                            width: parent.width;
                            clicked => {
                                root.repeat = root.repeat == 0 ? 1 : 0;
                                set-repeat(root.repeat);
                            }
                        }
                    }
                }
            }

            HorizontalLayout {
                width: 180px;
                alignment: LayoutAlignment.end;
                spacing: 5px;
                padding: 5px;

                VerticalLayout {
                    alignment: LayoutAlignment.center;
                    Text {
                        text: "\u{f057e}";
                        font-size: 18px;
                        font-family: "JetBrainsMono NFP";
                        color: Theme.txt2;
                        vertical-alignment: center;
                    }
                }

                VerticalLayout {
                    width: 80px;
                    alignment: LayoutAlignment.center;
                    CustomSlider {
                        height: 10px;
                        minimum: 0;
                        maximum: 100;
                        value: Math.round(root.volume * 100);
                        released(v) => {
                            root.volume = v / 100.0;
                            set-volume(root.volume);
                        }
                    }
                }

                VerticalLayout {
                    alignment: LayoutAlignment.center;
                    padding: 5px;
                    Text {
                        text: TimeUtils.ms_to_minsec(duration);
                        font-size: 18px;
                        horizontal-alignment: TextHorizontalAlignment.right;
                        color: Theme.txt1;
                    }
                }
            }
        }

        VerticalBox {
            alignment: LayoutAlignment.start;
            padding: 0px;
            padding-left: 20px;
            padding-right: 20px;
            CustomSlider {
                height: 10px;
                minimum: 0;
                enabled: root.duration != 0;
                value <=> root.value;
                maximum: root.duration;
                released(value) => {
                    seek(value)
                }
            }
        }
    }
}
