import { Slider, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { CustomSlider } from "CustomComp.slint";
import { Theme } from "Types.slint";

export global TimeUtils {
    pure public function ms_to_minsec(ms: int) -> string {
        let total_sec: int = ms / 1000;
        let min_str: int = total_sec / 60;
        let sec: int = Math.mod(total_sec, 60);
        let sec_str: string = sec < 10 ? "0" + sec : sec;
        return min_str + ":" + sec_str;
    }
}

export component PlayerView inherits Rectangle {
    height: 100px;
    background: Theme.bg2;
    border-radius: 15px;

    in-out property <int> value;
    in property <int> duration;
    in property <bool> is-paused;

    callback prev();
    callback pause();
    callback next();
    callback seek(float);

    VerticalLayout {
        padding: 5px;
        spacing: 0px;
        HorizontalLayout {
            padding: 10px;
            VerticalLayout {
                padding: 10px;
                alignment: LayoutAlignment.center;
                Text {
                    text: TimeUtils.ms_to_minsec(value);
                    font-size: 20px;
                    color: Theme.text;
                }
            }

            VerticalLayout {
                alignment: LayoutAlignment.center;
                HorizontalLayout {
                    alignment: LayoutAlignment.center;
                    spacing: 10px;

                    Rectangle {
                        width: 40px;
                        height: 40px;
                        border-radius: 20px;
                        background: prevTA.has-hover ? Theme.bg4 : Theme.bg3;
                        animate background { duration: 100ms; }
                        Text {
                            vertical-alignment: TextVerticalAlignment.center;
                            horizontal-alignment: TextHorizontalAlignment.center;
                            width: 40px;
                            height: 40px;

                            text: "󰒮";
                            font-size: 30px;
                            color: Theme.buttons;
                        }

                        prevTA := TouchArea {
                            height: parent.height;
                            width: parent.width;
                            clicked => {
                                prev()
                            }
                        }
                    }

                    Rectangle {
                        width: 40px;
                        height: 40px;
                        border-radius: 20px;
                        background: playTA.has-hover ? Theme.bg4 : Theme.bg3;
                        animate background { duration: 100ms; }
                        Text {
                            vertical-alignment: TextVerticalAlignment.center;
                            horizontal-alignment: TextHorizontalAlignment.center;
                            width: 40px;
                            height: 40px;

                            text: root.is-paused ? "" : "";
                            font-size: root.is-paused ? 25px : 30px;
                            color: Theme.buttons;
                        }

                        playTA := TouchArea {
                            height: parent.height;
                            width: parent.width;
                            clicked => {
                                pause();
                            }
                        }
                    }

                    Rectangle {
                        width: 40px;
                        height: 40px;
                        border-radius: 20px;
                        background: nextTA.has-hover ? Theme.bg4 : Theme.bg3;
                        animate background { duration: 100ms; }
                        Text {
                            vertical-alignment: TextVerticalAlignment.center;
                            horizontal-alignment: TextHorizontalAlignment.center;
                            width: 40px;
                            height: 40px;

                            text: "󰒭";
                            font-size: 30px;
                            color: Theme.buttons;
                        }

                        nextTA := TouchArea {
                            height: parent.height;
                            width: parent.width;
                            clicked => {
                                next()
                            }
                        }
                    }
                }
            }

            VerticalLayout {
                alignment: LayoutAlignment.center;
                padding: 10px;
                Text {
                    text: TimeUtils.ms_to_minsec(duration);
                    font-size: 20px;
                    horizontal-alignment: TextHorizontalAlignment.right;
                    color: Theme.text;
                }
            }
        }

        VerticalBox {
            alignment: LayoutAlignment.start;
            padding: 0px;
            padding-left: 20px;
            padding-right: 20px;
            CustomSlider {
                height: 10px;
                minimum: 0;
                enabled: root.duration != 0;
                value <=> root.value;
                maximum: root.duration;
                released(value) => {
                    seek(value)
                }
            }
        }
    }
}
