import { Theme, Tabs } from "Types.slint";
export component TabButton inherits Rectangle {
    in-out property <Tabs> active;
    in property <string> label;
    in property <Tabs> tab;
    callback button-clicked();
    Rectangle {
        background: active == tab ? Theme.bgd1 : Theme.bgd2;

        animate background { duration: 200ms; }
        animate border-color { duration: 200ms; }
        border-radius: 10px;
        Text {
            text: label;
            color: active == tab ? Theme.acct : Theme.txt1;
            animate color { duration: 200ms; }
            font-size: 25px;
            vertical-alignment: center;
            horizontal-alignment: center;
        }

        TouchArea {
            height: parent.height;
            width: parent.width;
            clicked => {
                active = tab;
                button-clicked();
            }
        }
    }
}

export component TabSelectorView inherits Rectangle {
    in-out property <Tabs> active-view;
    callback refresh-playlists();
    height: 60px;

    Rectangle {
        background: Theme.bgd2;
        border-radius: 15px;

        HorizontalLayout {
            padding: 5px;
            spacing: 5px;
            TabButton {
                label: "Search";
                tab: Tabs.Search;
                active <=> active-view;
            }

            TabButton {
                label: "Playlists";
                tab: Tabs.Playlists;
                active <=> active-view;
                button-clicked => {
                    refresh-playlists()
                }
            }
        }
    }
}
