import { Theme } from "Types.slint";
export component TabButton inherits Rectangle {
    in-out property <string> active;
    in property <string> label;
    callback button-clicked();
    Rectangle {
        background: active == label ? Theme.bg1 : Theme.bg2;

        animate background { duration: 100ms; }
        animate border-color { duration: 100ms; }
        border-radius: 10px;
        Text {
            text: label;
            color: active == label ? Theme.accent : Theme.text;
            animate color { duration: 100ms; }
            font-size: 20px;
            vertical-alignment: center;
            horizontal-alignment: center;
        }

        TouchArea {
            height: parent.height;
            width: parent.width;
            clicked => {
                active = label;
                button-clicked();
            }
        }
    }
}

export component TabSelectorView inherits Rectangle {
    in-out property <string> current-tab;
    in-out property <string> active-view;
    callback refresh-playlists();
    height: 100px;

    Rectangle {
        background: Theme.bg2;
        border-radius: 15px;

        VerticalLayout {
            padding: 5px;
            spacing: 5px;
            TabButton {
                label: "Search";
                active <=> active-view;
            }

            TabButton {
                label: "Playlists";
                active <=> active-view;
                button-clicked => {
                    refresh-playlists()
                }
            }
        }
    }
}
