export struct CurrentSong {
    title: string,
    artists: string,
    position: int,
    duration: int,
    is_paused: bool,
    song_uuid: string,
    album_art: image,
}

export enum Tabs {
    Search,
    Playlists
}

export struct Song {
    title: string,
    artists: string,
    album_art: image,
    id: string,
}

export struct PlaylistMinimal {
    title: string,
    length: int,
    id: string,
}

export struct Playlist {
    id: string,
    title: string,
    songs: [Song]
}

export global Theme {
    in-out property <color> bgd0: #11111b;
    in-out property <color> bgd1: #181825;
    in-out property <color> bgd2: #1e1e2e;
    in-out property <color> bgd3: #313244;
    in-out property <color> bgd4: #45475a;
    in-out property <color> txt1: #cdd6f4;
    in-out property <color> txt2: #a6adc8;
    in-out property <color> acct: #cba6f7;
    in-out property <color> srch: #45475a;
    in-out property <color> btns: #cdd6f4;
}
