import { QueueView, Song } from "QueueView.slint";
import { TabSelectorView } from "TabSelectorView.slint";
import { MainView } from "MainView.slint";
import { NowPlayingView } from "NowPlayingView.slint";
import { PlayerView } from "PlayerView.slint";
import { CurrentSong } from "Types.slint";
import "../assets/NotoSansJP-Regular.ttf";

export component AuroraPlayer inherits Window {
    callback queue-click(int);
    callback prev();
    callback pause();
    callback next();
    callback seek(float);

    in-out property <string> Title: "Nothing Playing";
    in-out property <string> Artists: "No artist";
    in-out property <image> AlbumArt: @image-url("../assets/placeholder.jpg");
    in-out property <int> position: 0;
    in-out property <bool> is_paused: true;
    in-out property <int> duration: 0;

    in-out property <[Song]> queue;

    in-out property <string> active-view: "Search";

    title: "Aurora Player";

    min-height: 650px;
    min-width: 1155px;
    preferred-height: 800px;
    preferred-width: 1422px;

    default-font-family: "Noto Sans JP";

    Rectangle {
        background: #111;
        HorizontalLayout {
            spacing: 5px;
            padding: 5px;
            VerticalLayout {
                spacing: 5px;

                TabSelectorView {
                    active-view <=> root.active-view;
                }

                QueueView {
                    queue: root.queue;
                    queue-click(n) => {
                        root.queue-click(n)
                    }
                }

                VerticalLayout {
                    NowPlayingView {
                        Title: root.Title;
                        Artists: root.Artists;
                        AlbumArt: root.AlbumArt;

                        width: 400px;
                        height: 100px;
                    }
                }
            }

            VerticalLayout {
                spacing: 5px;

                MainView {
                    active-view: root.active-view;
                }

                PlayerView {
                    pause => {
                        root.pause()
                    }
                    next => {
                        root.next()
                    }
                    prev => {
                        root.prev()
                    }
                    seek(value) => {
                        seek(value);
                        debug(value);
                    }
                    value <=> position;
                    duration: root.duration;
                    is-paused: root.is_paused;
                }
            }
        }
    }
}
