import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { ComboBox, SongList, PlList } from "CustomComp.slint";
import { Song, Playlist }from "Types.slint";

export component SearchView inherits VerticalBox {
    in-out property <string> searchMode: "By Title";
    in-out property <string> query: "";
    in property <[Song]> searchResults;
    callback submit(string, string);
    callback item-clicked(string);

    VerticalLayout {
        transform-rotation: 180deg;
        spacing: 5px;
        SongList {
            transform-rotation: 180deg;
            items: searchResults;
            item-clicked(id) => {
                item-clicked(id);
            }
        }

        HorizontalLayout {
            transform-rotation: 180deg;
            spacing: 5px;
            Rectangle {
                border-radius: 10px;
                height: 50px;
                background: #111;
                border-color: #00000033;
                border-width: 1px;
                HorizontalBox {
                    padding: 10px;
                    Image {
                        source: @image-url("../assets/search.png");
                        height: parent.height - 20px;
                        width: parent.height - 20px;
                    }

                    TextInput {
                        font-size: 20px;
                        vertical-alignment: center;
                        color: #eee;
                        text <=> query;
                        accepted => {
                            submit(query, searchMode);
                        }
                    }
                }
            }

            ComboBox {
                model: ["By Artist", "By Title"];
                current <=> searchMode;
            }
        }
    }
}

export component PlaylistView inherits VerticalBox {
    in property <[Playlist]> Playlists;
    padding: 10px;
    Text {
        text: "Playlists";
        color: #eee;
        font-size: 30px;
    }

    PlList {
        items: Playlists;
    }
}

export component MainView inherits Rectangle {
    background: #222;
    border-radius: 10px;
    in property <string> active-view;
    in property <[Song]> searchResults;
    in property <[Playlist]> Playlists;
    in property <bool> searchOverflow;
    callback query-submit(string, string);
    callback add(string);
    callback get-all-playlists();
    callback get-playlist(string);

    SearchView {
        visible: active-view == "Search";
        searchResults: root.searchResults;
        submit(q, m) => {
            query-submit(q, m);
            debug(q, m);
        }
        item-clicked(id) => {
            add(id);
        }
    }

    PlaylistView {
        visible: active-view == "Playlists";
        Playlists: root.Playlists;
    }
}
