import { Theme } from "Types.slint";
export component NowPlayingView inherits Rectangle {
    in property <string> Title;
    in property <string> Artists;
    in property <image> AlbumArt;
    background: Theme.bg2;
    border-radius: 15px;

    HorizontalLayout {
        padding: 10px;
        spacing: 10px;
        Rectangle {
            Image {
                source: AlbumArt;
                height: parent.height;
                width: parent.width;
            }

            height: 80px;
            width: 80px;
            clip: true;
            border-radius: 15px;
        }

        VerticalLayout {
            padding: 10px;

            HorizontalLayout {
                alignment: LayoutAlignment.start;
                Rectangle {
                    property <bool> should-scroll: song.preferred-width > 270px;
                    property <float> scroll-offset: 0;

                    height: song.preferred-height;
                    width: should-scroll ? 270px : song.preferred-width;
                    clip: true;

                    song := Text {
                        font-size: 20px;
                        text: Title;
                        y: 0;
                        x: should-scroll ? scroll-offset * 1px : 0;
                        color: Theme.text;
                    }

                    Text {
                        font-size: 20px;
                        text: Title;
                        y: 0;
                        x: should-scroll ? scroll-offset * 1px + song.preferred-width + 50px : 1000px;
                        visible: should-scroll;
                        color: Theme.text;
                    }

                    timer := Timer {
                        interval: 16ms;
                        running: should-scroll;
                        triggered => {
                            scroll-offset -= 1;
                            if (scroll-offset * 1px < -(song.preferred-width + 50px)) {
                                scroll-offset = 0;
                            }
                        }
                    }
                }
            }

            HorizontalLayout {
                alignment: LayoutAlignment.start;
                Rectangle {
                    property <bool> should-scroll: artist.preferred-width > 270px;
                    property <float> scroll-offset: 0;

                    height: artist.preferred-height;
                    width: should-scroll ? 270px : artist.preferred-width;
                    clip: true;

                    artist := Text {
                        font-size: 16px;
                        text: Artists;
                        y: 0;
                        x: should-scroll ? scroll-offset * 1px : 0;
                        color: Theme.text2;
                    }

                    Text {
                        font-size: 16px;
                        text: Artists;
                        y: 0;
                        x: should-scroll ? scroll-offset * 1px + artist.preferred-width + 30px : 1000px;
                        visible: should-scroll;
                        color: Theme.text2;
                    }

                    timer2 := Timer {
                        interval: 16ms;
                        running: should-scroll;
                        triggered => {
                            scroll-offset -= 1;
                            if (scroll-offset * 1px < -(artist.preferred-width + 30px)) {
                                scroll-offset = 0;
                            }
                        }
                    }
                }
            }
        }
    }
}
