import { NowPlayingView } from "NowPlayingView.slint";
import { Song } from "Types.slint";
import { ScrollView } from "CustomComp.slint";


export component QueueView inherits Rectangle {
    in property <[Song]> queue;
    callback queue-click(int);

    width: 400px;
    background: #333;
    border-radius: 10px;
    clip: true;

    HorizontalLayout {
        scroll := ScrollView {
            content-height: 105px * queue.length - 5px;
            transform-rotation: 180deg;

            VerticalLayout {
                spacing: 5px;
                for item[i] in queue: NowPlayingView {
                    transform-rotation: 180deg;
                    Artists: item.artists;
                    AlbumArt: item.album_art;
                    Title: item.title;
                    border-radius: 0px;
                    background: touch.has-hover ? #444 : #333;
                    animate background { duration: 200ms; }
                    touch := TouchArea {
                        width: parent.width;
                        height: parent.height;

                        clicked => {
                            queue-click(i);
                            //scroll.viewport-y = 0;
                        }
                    }
                }
            }
        }
    }
}
