export component TabButton inherits Rectangle {
    in-out property <string> active;
    in property <string> label;
    Rectangle {
        background: active == label ? #689d6a : #222;
        animate background { duration: 100ms; }
        border-radius: 5px;
        Text {
            text: label;
            color: #eee;
            font-size: 20px;
            vertical-alignment: center;
            horizontal-alignment: center;
        }

        TouchArea {
            height: parent.height;
            width: parent.width;
            clicked => {
                active = label
            }
        }
    }
}

export component TabSelectorView inherits Rectangle {
    in-out property <string> current-tab;
    in-out property <string> active-view;
    height: 100px;

    Rectangle {
        background: #222;
        border-radius: 10px;
        VerticalLayout {
            padding: 5px;
            spacing: 5px;
            TabButton {
                label: "Search";
                active <=> active-view;
            }

            TabButton {
                label: "Playlists";
                active <=> active-view;
            }
        }
    }
}
