export component Button inherits Rectangle {
    in-out property <string> active;
    in property <string> label;
    VerticalLayout {
        Rectangle {
            background: active == label ? #333 : #222;
            animate background { duration: 100ms; }
            border-radius: 10px;
            Text {
                text: label;
                color: #eee;
                font-size: 20px;
                vertical-alignment: center;
                horizontal-alignment: center;
            }

            TouchArea {
                height: parent.height;
                width: parent.width;
                clicked => {
                    active = label
                }
            }
        }
    }
}

export component TabSelectorView inherits Rectangle {
    in-out property <string> current-tab;
    in-out property <string> active-view;
    height: 100px;
    background: #333;
    border-radius: 10px;

    VerticalLayout {
        padding: 5px;
        Rectangle {
            background: #222;
            border-radius: 10px;
            VerticalLayout {
                padding: 5px;
                spacing: 5px;
                Button {
                    label: "Search";
                    active <=> active-view;
                }

                Button {
                    label: "Playlists";
                    active <=> active-view;
                }
            }
        }
    }
}
